# cv-arxiv-daily configuration

# category-based daily fetch
daily_category: true
category_list: ["cs.CV"]

# output directories
json_dir: './json'
md_dir: './md'
md_readme_path: 'README.md'

show_badge: false
