import os
import re
import json
import glob
import yaml
import logging
import argparse
import datetime
import requests

logging.basicConfig(format='[%(asctime)s %(levelname)s] %(message)s',
                    datefmt='%m/%d/%Y %H:%M:%S',
                    level=logging.INFO)

github_url = "https://api.github.com/search/repositories"
arxiv_url = "http://arxiv.org/"

def load_config(config_file:str) -> dict:
    '''
    config_file: input config file path
    return: a dict of configuration
    '''
    # make filters pretty
    def pretty_filters(**config) -> dict:
        keywords = dict()
        EXCAPE = '\"'
        QUOTA = '' # NO-USE
        OR = ' OR ' # TODO
        def parse_filters(filters:list):
            ret = ''
            for idx in range(0,len(filters)):
                filter = filters[idx]
                if len(filter.split()) > 1:
                    ret += (EXCAPE + filter + EXCAPE)
                else:
                    ret += (QUOTA + filter + QUOTA)
                if idx != len(filters) - 1:
                    ret += OR
            return ret
        for k,v in config['keywords'].items():
            keywords[k] = parse_filters(v['filters'])
        return keywords
    with open(config_file,'r') as f:
        config = yaml.load(f,Loader=yaml.FullLoader)
        if 'keywords' in config:
            config['kv'] = pretty_filters(**config)
        else:
            config['kv'] = {}
        logging.info(f'config = {config}')
    return config

def get_authors(authors, first_author = False):
    output = str()
    if first_author == False:
        output = ", ".join(str(author) for author in authors)
    else:
        output = authors[0]
    return output
def sort_papers(papers):
    output = dict()
    keys = list(papers.keys())
    keys.sort(reverse=True)
    for key in keys:
        output[key] = papers[key]
    return output

def get_code_link(qword:str) -> str:
    """
    This short function was auto-generated by ChatGPT.
    I only renamed some params and added some comments.
    @param qword: query string, eg. arxiv ids and paper titles
    @return paper_code in github: string, if not found, return None
    """
    # query = f"arxiv:{arxiv_id}"
    query = f"{qword}"
    params = {
        "q": query,
        "sort": "stars",
        "order": "desc"
    }
    r = requests.get(github_url, params=params)
    results = r.json()
    code_link = None
    if results["total_count"] > 0:
        code_link = results["items"][0]["html_url"]
    return code_link

def scrape_arxiv_listing(category, max_results=None):
    """
    Scrape arXiv /new listing page for today's papers with abstracts.
    @param category: str, arXiv category code (e.g. cs.CV)
    @param max_results: int or None, max papers to return (None = all)
    @return: (data, data_web) dicts keyed by category name
    """
    url = f"https://arxiv.org/list/{category}/new?skip=0&show=2000"
    logging.info(f"Fetching {url}")
    resp = requests.get(url, timeout=60)
    html = resp.text

    # date: <h3>Showing new listings for Thursday, 28 May 2026</h3>
    date_m = re.search(r'<h3>Showing new listings for \w+, (\d{1,2} \w+ \d{4})</h3>', html)
    if date_m:
        try:
            current_date = datetime.datetime.strptime(date_m.group(1), '%d %B %Y').date()
        except ValueError:
            current_date = datetime.date.today()
    else:
        current_date = datetime.date.today()
    date_str = current_date.isoformat()

    content = dict()
    content_to_web = dict()

    entries = list(re.finditer(
        r'<a\s+name=[\'"]item\d+[\'"]>.*?</a>\s*<a\s+href\s*=\s*["\']/abs/(\d+\.\d+)[^>]*>\s*arXiv:\1',
        html
    ))

    for entry in entries:
        if max_results and len(content) >= max_results:
            break

        paper_id = entry.group(1)
        dd_start = html.find('<dd>', entry.end())
        if dd_start == -1:
            continue
        dd_end = html.find('</dd>', dd_start)
        if dd_end == -1:
            continue
        dd_block = html[dd_start:dd_end]

        # title
        title_m = re.search(
            r"<div\s+class=['\"]list-title[^'\"]*['\"][^>]*>.*?<span[^>]*>Title:</span>\s*(.+?)\s*</div>",
            dd_block, re.DOTALL
        )
        title = ''
        if title_m:
            title = re.sub(r'<[^>]+>', '', title_m.group(1)).strip()
            title = re.sub(r'\s+', ' ', title)

        # authors
        authors = ''
        first_author = ''
        authors_m = re.search(
            r"<div\s+class=['\"]list-authors['\"][^>]*>(.+?)</div>",
            dd_block, re.DOTALL
        )
        if authors_m:
            author_texts = re.findall(r'<a[^>]*>([^<]+)</a>', authors_m.group(1))
            if author_texts:
                first_author = author_texts[0].strip()
                authors = ', '.join(a.strip() for a in author_texts)

        # abstract: <p class='mathjax'>...</p>
        abstract = ''
        abstract_m = re.search(
            r"<p\s+class=['\"]mathjax['\"][^>]*>(.+?)</p>",
            dd_block, re.DOTALL
        )
        if abstract_m:
            abstract = re.sub(r'<[^>]+>', '', abstract_m.group(1)).strip()
            abstract = re.sub(r'\s+', ' ', abstract)

        paper_url = arxiv_url + 'abs/' + paper_id
        paper_data = {
            "title": title,
            "authors": authors,
            "first_author": first_author,
            "abstract": abstract,
            "date": date_str,
            "url": paper_url,
        }
        content[paper_id] = paper_data
        content_to_web[paper_id] = f"- {date_str}, **{title}**, {first_author} et.al., Paper: [{paper_url}]({paper_url})\n"
        logging.info(f"Time = {date_str} title = {title} author = {first_author}")

    logging.info(f"Scraped {len(content)} papers from {category}")
    data = {category: content}
    data_web = {category: content_to_web}
    return data, data_web

def get_daily_papers(topic, query="slam", max_results=2):
    """Deprecated keyword-based fetch. Requires arxiv package. Kept for backward compat."""
    logging.warning("get_daily_papers() requires the arxiv package. Use scrape_arxiv_listing() instead.")
    return {topic: {}}, {topic: {}}

def get_daily_papers_by_category(category, max_results=None):
    """Fetch all papers in a given arXiv category via HTML scraping."""
    return scrape_arxiv_listing(category, max_results=max_results)

def update_paper_links(filename):
    '''
    weekly update paper links in json file.
    Note: PapersWithCode API is deprecated; this is kept for backward compat.
    '''
    logging.info(f"update_paper_links: PapersWithCode API deprecated, skipping {filename}")

def update_json_file(filename,data_dict):
    '''
    daily update json file using data_dict
    '''
    with open(filename,"r") as f:
        content = f.read()
        if not content:
            m = {}
        else:
            m = json.loads(content)

    json_data = m.copy()

    # update papers in each keywords
    for data in data_dict:
        for keyword in data.keys():
            papers = data[keyword]

            if keyword in json_data.keys():
                json_data[keyword].update(papers)
            else:
                json_data[keyword] = papers

    with open(filename,"w") as f:
        json.dump(json_data,f)

def save_date_json(filepath, data_dict):
    '''
    write today's papers to a date-stamped JSON file.
    if re-run on the same day, merge with existing data.
    '''
    if os.path.exists(filepath):
        with open(filepath, "r") as f:
            content = f.read()
            existing = json.loads(content) if content else {}
    else:
        existing = {}

    for data in data_dict:
        for keyword, papers in data.items():
            if keyword in existing:
                existing[keyword].update(papers)
            else:
                existing[keyword] = papers

    with open(filepath, "w") as f:
        json.dump(existing, f)

def merge_date_jsons(directory, prefix):
    '''
    merge all date-stamped JSON files matching {directory}/{prefix}-YYYY-MM-DD.json.
    returns a merged dict with the same structure as the old single JSON.
    '''
    pattern = os.path.join(directory, f"{prefix}-????-??-??.json")
    merged = {}
    for filepath in sorted(glob.glob(pattern)):
        with open(filepath, "r") as f:
            content = f.read()
            if not content:
                continue
            data = json.loads(content)
            for topic, papers in data.items():
                if topic in merged:
                    merged[topic].update(papers)
                else:
                    merged[topic] = papers
    return merged

def json_to_md(filename,md_filename,
               task = '',
               to_web = False,
               use_title = True,
               use_tc = True,
               show_badge = True,
               use_b2t = True,
               data = None):
    """
    @param filename: str (ignored if data is provided)
    @param md_filename: str
    @param data: dict, optional. If provided, used directly instead of reading from file.
    @return None
    """
    def pretty_math(s:str) -> str:
        ret = ''
        match = re.search(r"\$.*\$", s)
        if match == None:
            return s
        math_start,math_end = match.span()
        space_trail = space_leading = ''
        if s[:math_start][-1] != ' ' and '*' != s[:math_start][-1]: space_trail = ' '
        if s[math_end:][0] != ' ' and '*' != s[math_end:][0]: space_leading = ' '
        ret += s[:math_start]
        ret += f'{space_trail}${match.group()[1:-1].strip()}${space_leading}'
        ret += s[math_end:]
        return ret

    DateNow = datetime.date.today()
    DateNow = str(DateNow)
    DateNow = DateNow.replace('-','.')

    if data is None:
        with open(filename,"r") as f:
            content = f.read()
            if not content:
                data = {}
            else:
                data = json.loads(content)

    # clean README.md if daily already exist else create it
    with open(md_filename,"w+") as f:
        pass

    # write data into README.md
    with open(md_filename,"a+") as f:

        if (use_title == True) and (to_web == True):
            f.write("---\n" + "layout: default\n" + "---\n\n")

        # if show_badge == True:
        #     f.write(f"[![Contributors][contributors-shield]][contributors-url]\n")
        #     f.write(f"[![Forks][forks-shield]][forks-url]\n")
        #     f.write(f"[![Stargazers][stars-shield]][stars-url]\n")
        #     f.write(f"[![Issues][issues-shield]][issues-url]\n\n")

        if use_title == True:
            #f.write(("<p align="center"><h1 align="center"><br><ins>CV-ARXIV-DAILY"
            #         "</ins><br>Automatically Update CV Papers Daily</h1></p>\n"))
            f.write("## Updated on " + DateNow + "\n")
        else:
            f.write("> Updated on " + DateNow + "\n")

        # TODO: add usage
        f.write("> Usage instructions: [here](./docs/README.md#usage)\n\n")

        #Add: table of contents
        if use_tc == True:
            f.write("<details>\n")
            f.write("  <summary>Table of Contents</summary>\n")
            f.write("  <ol>\n")
            for keyword in data.keys():
                day_content = data[keyword]
                if not day_content:
                    continue
                kw = keyword.replace(' ','-')
                f.write(f"    <li><a href=#{kw.lower()}>{keyword}</a></li>\n")
            f.write("  </ol>\n")
            f.write("</details>\n\n")

        for keyword in data.keys():
            day_content = data[keyword]
            if not day_content:
                continue
            # the head of each part
            f.write(f"## {keyword}\n\n")

            if use_title == True :
                if to_web == False:
                    f.write("|Publish Date|Title|Authors|Abstract|PDF|\n" + "|---|---|---|---|---|\n")
                else:
                    f.write("| Publish Date | Title | Authors | Abstract | PDF |\n")
                    f.write("|:---------|:-----------------------|:---------|:------|:------|\n")

            # sort papers by date (descending), then by paper_id
            sorted_papers = sorted(day_content.items(),
                key=lambda x: (x[1].get('date', '') if isinstance(x[1], dict) else ''),
                reverse=True)

            for paper_id, v in sorted_papers:
                if v is None:
                    continue
                if isinstance(v, dict):
                    title = pretty_math(v.get('title', ''))
                    date_val = v.get('date', '')
                    first_author = v.get('first_author', '')
                    abstract = v.get('abstract', '')[:200] + ('...' if len(v.get('abstract', '')) > 200 else '')
                    url = v.get('url', '')
                    if to_web == False:
                        f.write(f"|**{date_val}**|**{title}**|{first_author} et.al.|{abstract}|[{paper_id}]({url})|\n")
                    else:
                        f.write(f"| {date_val} | {title} | {first_author} et.al. | {abstract} | [{paper_id}]({url}) |\n")
                else:
                    # backward compat: old pipe-delimited format
                    f.write(pretty_math(str(v)))

            f.write(f"\n")

            #Add: back to top
            if use_b2t:
                top_info = f"#Updated on {DateNow}"
                top_info = top_info.replace(' ','-').replace('.','')
                f.write(f"<p align=right>(<a href={top_info.lower()}>back to top</a>)</p>\n\n")

        if show_badge == True:
            # we don't like long string, break it!
            f.write((f"[contributors-shield]: https://img.shields.io/github/"
                     f"contributors/Vincentqyw/cv-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[contributors-url]: https://github.com/Vincentqyw/"
                     f"cv-arxiv-daily/graphs/contributors\n"))
            f.write((f"[forks-shield]: https://img.shields.io/github/forks/Vincentqyw/"
                     f"cv-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[forks-url]: https://github.com/Vincentqyw/"
                     f"cv-arxiv-daily/network/members\n"))
            f.write((f"[stars-shield]: https://img.shields.io/github/stars/Vincentqyw/"
                     f"cv-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[stars-url]: https://github.com/Vincentqyw/"
                     f"cv-arxiv-daily/stargazers\n"))
            f.write((f"[issues-shield]: https://img.shields.io/github/issues/Vincentqyw/"
                     f"cv-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[issues-url]: https://github.com/Vincentqyw/"
                     f"cv-arxiv-daily/issues\n\n"))

    logging.info(f"{task} finished")

def demo(**config):
    data_collector = []
    data_collector_web= []

    keywords = config['kv']
    max_results = config['max_results']
    publish_readme = config['publish_readme']
    publish_gitpage = config['publish_gitpage']
    publish_wechat = config['publish_wechat']
    show_badge = config['show_badge']

    daily_category = config.get('daily_category', False)
    category_list = config.get('category_list', [])
    category_max_results = config.get('category_max_results', None)

    today = datetime.date.today().isoformat()

    b_update = config['update_paper_links']
    logging.info(f'Update Paper Link = {b_update}')
    if config['update_paper_links'] == False:
        logging.info(f"GET daily papers begin")

        # category-based fetch (no keyword filtering)
        if daily_category:
            for cat in category_list:
                logging.info(f"Category: {cat}")
                data, data_web = get_daily_papers_by_category(cat,
                                            max_results = category_max_results)
                data_collector.append(data)
                data_collector_web.append(data_web)

        # keyword-based fetch
        for topic, keyword in keywords.items():
            logging.info(f"Keyword: {topic}")
            data, data_web = get_daily_papers(topic, query = keyword,
                                            max_results = max_results)
            data_collector.append(data)
            data_collector_web.append(data_web)
            print("\n")
        logging.info(f"GET daily papers end")

    def _date_pipeline(json_path, md_path, dc, **md_kwargs):
        """save to date JSON, merge all, generate MD."""
        json_dir = os.path.dirname(json_path)
        json_prefix = os.path.splitext(os.path.basename(json_path))[0]
        date_file = os.path.join(json_dir, f"{json_prefix}-{today}.json")

        if config['update_paper_links']:
            for fp in sorted(glob.glob(os.path.join(json_dir, f"{json_prefix}-????-??-??.json"))):
                update_paper_links(fp)
        else:
            save_date_json(date_file, dc)

        merged = merge_date_jsons(json_dir, json_prefix)
        json_to_md(json_path, md_path, data=merged, **md_kwargs)

    # 1. update README.md file
    if publish_readme:
        _date_pipeline(config['json_readme_path'], config['md_readme_path'],
                       data_collector, task='Update Readme', show_badge=show_badge)

    # 2. update docs/index.md file (to gitpage)
    if publish_gitpage:
        _date_pipeline(config['json_gitpage_path'], config['md_gitpage_path'],
                       data_collector, task='Update GitPage',
                       to_web=True, show_badge=show_badge,
                       use_tc=False, use_b2t=False)

    # 3. Update docs/wechat.md file
    if publish_wechat:
        _date_pipeline(config['json_wechat_path'], config['md_wechat_path'],
                       data_collector_web, task='Update Wechat',
                       to_web=False, use_title=False, show_badge=show_badge)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--config_path',type=str, default='config.yaml',
                            help='configuration file path')
    parser.add_argument('--update_paper_links', default=False,
                        action="store_true",help='whether to update paper links etc.')
    args = parser.parse_args()
    config = load_config(args.config_path)
    config = {**config, 'update_paper_links':args.update_paper_links}
    demo(**config)
